### ISSUE TITLE
Error when running tests

### ISSUE THREAD

**Issue by sewagodimo** [praekeltfoundation/molo#540]

**Comment by nathanbegbie** [comment]
@sewagodimo can you please provide a bit more detail on what the error was.

Especially when experiencing errors, it's good to include the following details:

What you did (i.e. explicit steps that you followed to get the error).
What you expected would happen.
What actually happened (including the error output here is helpful)
Additional information that might be relevant (e.g. what operating system, version of python, django etc.)

This gives the person responding to your ticket valuable insight into how you might go about solving the issues that you're having.

We don't always get this right, but sometimes there's a JIRA ticket that we can link to instead which will include the details.

Here's some further reading on issues: https://wiredcraft.com/blog/how-we-write-our-github-issues/

**Comment by nathanbegbie** [comment]
If you solved this particular problem, please comment and close this issue :)
